version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_URL=mongodb://mongodb:27017/ph-uni
      - BCRYPT_SALT_ROUND=${BCRYPT_SALT_ROUND}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_TOKEN_DURATION=${JWT_ACCESS_TOKEN_DURATION}
      - JWT_REFRESH_TOKEN_DURATION=${JWT_REFRESH_TOKEN_DURATION}
      - RESET_PASSWORD_UI_LINK=${RESET_PASSWORD_UI_LINK}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
    tmpfs:
      - /app/uploads:rw,noexec,nosuid,size=100M
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:
